### ISSUE TITLE
XBMC crashes after a while of running Spotimc beta 4

### ISSUE THREAD

**Issue by kusen81** [mazkolain-zz/spotimc#127]
XBMC crashes all of a sudden when using the plugin and drops out to debian console. The crash seems random. I´m not sure what info you need but i´ve supplied the end of the XBMC crash log down here.

00:12:03 T:140206362502912  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "HEAD /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206362502912  NOTICE: .
00:12:03 T:140206362502912  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "GET /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206362502912  NOTICE: .
00:12:03 T:140206270183168  NOTICE: Thread CFileCache start, auto delete: false
00:12:03 T:140207284713376   ERROR: Init: Error creating demuxer
00:12:03 T:140206396073728  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "GET /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206396073728  NOTICE: .
00:12:03 T:140206270183168  NOTICE: Thread CFileCache start, auto delete: false
00:12:03 T:140207284713376   ERROR: ADPCMCodec: error opening file http://127.0.0.1:8082/track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6|X-Spotify-Token=90a1379d5e9f0e2e687875d6a2d53d797a630349&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3AUnknown%29!
00:12:03 T:140206345717504  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "GET /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206345717504  NOTICE: .
00:12:03 T:140206270183168  NOTICE: Thread CFileCache start, auto delete: false
00:12:03 T:140206370895616  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "GET /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206370895616  NOTICE: .
00:12:03 T:140206270183168 WARNING: FillBuffer: curl failed with code 33
00:12:03 T:140206270183168   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
00:12:03 T:140206270183168   ERROR: Process, error 115 seeking. seek returned -1
00:12:03 T:140206337324800  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "GET /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206337324800  NOTICE: .
00:12:03 T:140206337324800   ERROR: [13/Sep/2013:00:12:03]  Traceback (most recent call last):
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 169, in trap
                                                return func(_args, *_kwargs)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 261, in next
                                                return self.iter_response.next()
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/httpproxy.py", line 288, in _write_file_content
                                                frame, has_frames = buf.get_frame_wait(frame_num)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 340, in get_frame_wait
                                                return self.get_frame(frame_num)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 311, in get_frame
                                                raise BufferError("Frame number #%d gone, too late my friend." % frame_num)
                                            BufferError: Frame number #0 gone, too late my friend.
00:12:03 T:140206337324800  NOTICE: .
00:12:03 T:140206337324800   ERROR: [13/Sep/2013:00:12:03]  Traceback (most recent call last):
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 193, in trap
                                                self.start_response(s, h, _sys.exc_info())
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 169, in trap
                                                return func(_args, *_kwargs)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 261, in next
                                                return self.iter_response.next()
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/httpproxy.py", line 288, in _write_file_content
                                                frame, has_frames = buf.get_frame_wait(frame_num)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 340, in get_frame_wait
                                                return self.get_frame(frame_num)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 311, in get_frame
                                                raise BufferError("Frame number #%d gone, too late my friend." % frame_num)
                                            BufferError: Frame number #0 gone, too late my friend.
00:12:03 T:140206337324800  NOTICE: .
00:12:03 T:140206337324800   ERROR: BufferError('Frame number #0 gone, too late my friend.',)
00:12:03 T:140206337324800  NOTICE: .
00:12:03 T:140206337324800   ERROR: Traceback (most recent call last):
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
                                                req.respond()
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
                                                self.server.gateway(self).respond()
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/wsgiserver/wsgiserver2.py", line 2117, in respond
                                                for chunk in response:
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 161, in next
                                                return self.trap(self.iter_response.next)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 193, in trap
                                                self.start_response(s, h, _sys.exc_info())
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 169, in trap
                                                return func(_args, *_kwargs)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 261, in next
                                                return self.iter_response.next()
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/httpproxy.py", line 288, in _write_file_content
                                                frame, has_frames = buf.get_frame_wait(frame_num)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 340, in get_frame_wait
                                                return self.get_frame(frame_num)
                                              File "/home/kusen81/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 311, in get_frame
                                                raise BufferError("Frame number #%d gone, too late my friend." % frame_num)
                                            BufferError: Frame number #0 gone, too late my friend.
00:12:03 T:140206337324800  NOTICE: .
00:12:03 T:140206270183168  NOTICE: Thread CFileCache start, auto delete: false
00:12:03 T:140206379288320  NOTICE: 127.0.0.1 - - [13/Sep/2013:00:12:03] "GET /track/36r1vIeGj9dUfCohNpYlJj.wav?idx=6 HTTP/1.1" 200 38455244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:Unknown)"
00:12:03 T:140206379288320  NOTICE: .
00:12:03 T:140206270183168 WARNING: FillBuffer: curl failed with code 33
00:12:03 T:140206270183168   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
00:12:03 T:140206270183168   ERROR: Process, error 115 seeking. seek returned -1
00:12:03 T:140206270183168 WARNING: FillBuffer: curl failed with code 18
00:12:03 T:140206270183168 WARNING: FillBuffer: Reconnect, (re)try 1

**Comment by mazkolain-zz** [comment]
Hello,

In order to get the big picture of what's going on I would like to see the full log file (platform info, arch, etc.). Yo can post here a pastebin link of it.

Also, does it happen in the middle of a track or especially when tracks are started?

Thanks for reporting!

**Comment by MrFly** [comment]
Hi,

similar from me. Spotimc causes XBMC to restart in middle of a track without any user actions around the time the error occured. 

Here is the xbmc.log:

http://pastebin.com/tw38A2Vb

Thank you! Great piece of software...

Edit: Ehm, if you need other logs (network e.g.) please leave a message....

Edit2: I'm using OpenELEC 3.2.0

**Comment by ZenithDK** [comment]
Just chiming in to says I have the same issue - I am on Ubuntu 13.04 using a ppa for XMBC on a Zotac ID83 

uname -a:
Linux meridian 3.8.0-30-generic #44-Ubuntu SMP Thu Aug 22 20:52:24 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Will attach XBMC log next time I see it crash.

**Comment by ZenithDK** [comment]
I'm using XBMC 12.2 - not a PPA as I said.

Here's a bunch of crashlogs, not sure if all of them are spotimc related though, but you can look at them if necessary: http://peecee.dk/upload/view/422006

The latest crash log:
http://pastebin.com/ukVGfFxY

Trying a paste of the crash here:

```
21:05:52 T:140572081751808  NOTICE: Thread CFileCache start, auto delete: false
21:05:52 T:140575185409920   ERROR: Init: Error creating demuxer
21:05:52 T:140572291475200  NOTICE: 127.0.0.1 - - [22/Sep/2013:21:05:52] "GET /track/28W5lTZMClVz9fLt6iiaJN.wav?idx=19 HTTP/1.1" 200 33339644 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:32b1a5e)"
21:05:52 T:140572291475200  NOTICE: .
21:05:52 T:140572081751808  NOTICE: Thread CFileCache start, auto delete: false
21:05:52 T:140572325046016  NOTICE: 127.0.0.1 - - [22/Sep/2013:21:05:52] "GET /track/28W5lTZMClVz9fLt6iiaJN.wav?idx=19 HTTP/1.1" 200 33339644 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:32b1a5e)"
21:05:52 T:140572325046016  NOTICE: .
21:05:52 T:140575185409920   ERROR: ADPCMCodec: error opening file http://127.0.0.1:8081/track/28W5lTZMClVz9fLt6iiaJN.wav?idx=19|X-Spotify-Token=6379b48a192dc525e9664215553892fdf3c6b8c5&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A32b1a5e%29!
21:05:52 T:140572199220992  NOTICE: 127.0.0.1 - - [22/Sep/2013:21:05:52] "GET /track/28W5lTZMClVz9fLt6iiaJN.wav?idx=19 HTTP/1.1" 200 33339644 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:32b1a5e)"
21:05:52 T:140572199220992  NOTICE: .
21:05:52 T:140572081751808  NOTICE: Thread CFileCache start, auto delete: false
21:05:52 T:140572333438720  NOTICE: 127.0.0.1 - - [22/Sep/2013:21:05:52] "GET /track/28W5lTZMClVz9fLt6iiaJN.wav?idx=19 HTTP/1.1" 200 33339644 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:32b1a5e)"
21:05:52 T:140572333438720  NOTICE: .
21:05:52 T:140572081751808 WARNING: FillBuffer: curl failed with code 33
21:05:52 T:140572081751808   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
21:05:52 T:140572081751808   ERROR: Process, error 115 seeking. seek returned -1
21:05:52 T:140572308260608  NOTICE: 127.0.0.1 - - [22/Sep/2013:21:05:52] "GET /track/28W5lTZMClVz9fLt6iiaJN.wav?idx=19 HTTP/1.1" 200 33339644 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:32b1a5e)"
21:05:52 T:140572308260608  NOTICE: .
21:05:52 T:140572081751808  NOTICE: Thread CFileCache start, auto delete: false
21:05:52 T:140572308260608   ERROR: [22/Sep/2013:21:05:52]  Traceback (most recent call last):
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 169, in trap
                                                return func(*args, **kwargs)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 261, in next
                                                return self.iter_response.next()
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/httpproxy.py", line 288, in _write_file_content
                                                frame, has_frames = buf.get_frame_wait(frame_num)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 340, in get_frame_wait
                                                return self.get_frame(frame_num)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 311, in get_frame
                                                raise BufferError("Frame number #%d gone, too late my friend." % frame_num)
                                            BufferError: Frame number #24 gone, too late my friend.
21:05:52 T:140572308260608  NOTICE: .
21:05:52 T:140572308260608   ERROR: [22/Sep/2013:21:05:52]  Traceback (most recent call last):
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 193, in trap
                                                self.start_response(s, h, _sys.exc_info())
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 169, in trap
                                                return func(*args, **kwargs)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 261, in next
                                                return self.iter_response.next()
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/httpproxy.py", line 288, in _write_file_content
                                                frame, has_frames = buf.get_frame_wait(frame_num)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 340, in get_frame_wait
                                                return self.get_frame(frame_num)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 311, in get_frame
                                                raise BufferError("Frame number #%d gone, too late my friend." % frame_num)
                                            BufferError: Frame number #24 gone, too late my friend.
21:05:52 T:140572308260608  NOTICE: .
21:05:52 T:140572308260608   ERROR: BufferError('Frame number #24 gone, too late my friend.',)
21:05:52 T:140572308260608  NOTICE: .
21:05:52 T:140572308260608   ERROR: Traceback (most recent call last):
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
                                                req.respond()
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
                                                self.server.gateway(self).respond()
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/wsgiserver/wsgiserver2.py", line 2117, in respond
                                                for chunk in response:
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 161, in next
                                                return self.trap(self.iter_response.next)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 193, in trap
                                                self.start_response(s, h, _sys.exc_info())
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 169, in trap
                                                return func(*args, **kwargs)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cpwsgi.py", line 261, in next
                                                return self.iter_response.next()
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/httpproxy.py", line 288, in _write_file_content
                                                frame, has_frames = buf.get_frame_wait(frame_num)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 340, in get_frame_wait
                                                return self.get_frame(frame_num)
                                              File "/home/lasse/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypesProxy.egg/spotifyproxy/audio.py", line 311, in get_frame
                                                raise BufferError("Frame number #%d gone, too late my friend." % frame_num)
                                            BufferError: Frame number #24 gone, too late my friend.
```

**Comment by kusen81** [comment]
Hello again, im not sure but i think it hung in the middle of a track when this log was generated. Here is the pastebin:

http://pastebin.com/dwNU1kfM

**Comment by alex-caelus** [comment]
For me it crashed between songs and It had been running fine for several songs before this happened.
The timings seem random but spotimc always crashes like this sooner or later. It's been this way for many months but I have not had the time to report it.

http://pastebin.com/55yv3DrK

Sorry for this "me too" post, but I felt I wanted to contribute my log, just in case it will help you.

**Comment by mazkolain-zz** [comment]
@alex-caelus thanks for the log report. I'm currently focused on this issue but I'm having problems to reliably reproduce it, so having several log files at hand may help.

Regards

**Comment by ZenithDK** [comment]
Another crash log can be found here: http://pastebin.com/xWxgyG82  (taken from http://forum.xbmc.org/showthread.php?tid=125147&pid=1536318#pid15363189)

**Comment by MrFly** [comment]
Hi, me again.

Got another crash (there were a few, but this time I've got time to leave a log) today. It happened again in the middle of a track I think. It's just a feeling, but could it be, that this crashes happens if spotimc is preloading for the next track (e.g. if "fade tracks" is enabled) ?

Here's the log: http://pastebin.com/1kS1mnpx

Good luck!

**Comment by MrFly** [comment]
Hi, me again (again),

tried to produce the error with debug log and got it. Here's the log with debug activated in xbmc. Maybe there are some useful informations u don't get in normal log:

http://pastebin.com/SDzx2qJr

Have fun :-)

**Comment by mazkolain-zz** [comment]
This issue should be fixed now.

I tested this playing a day-long playlist with no interruptions or crashes.

**Comment by ZenithDK** [comment]
Awesome - will test this soon.

**Comment by MrFly** [comment]
Can't get this to work, downloaded and installed spotimc-master from here. What am I missing?

20:30:34 T:140200540006144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named spotify
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/spotimc-master/spotimc.py", line 39, in <module>
                                                from spotimcgui.main import main
                                              File "/storage/.xbmc/addons/spotimc-master/resources/libs/spotimcgui/main.py", line 25, in <module>
                                                import windows
                                              File "/storage/.xbmc/addons/spotimc-master/resources/libs/spotimcgui/windows.py", line 24, in <module>
                                                import views.newstuff
                                              File "/storage/.xbmc/addons/spotimc-master/resources/libs/spotimcgui/views/newstuff.py", line 24, in <module>
                                                from spotimcgui.views import album
                                              File "/storage/.xbmc/addons/spotimc-master/resources/libs/spotimcgui/views/album.py", line 24, in <module>
                                                from spotify import albumbrowse, session, track as _track, image
                                            ImportError: No module named spotify
                                            -->End of Python script error report<--

Looks like there's no libspotify ?

**Comment by mazkolain-zz** [comment]
@MrFly This error appears because the copy you downloaded is missing some dependencies (python modules, libspotify dll's, etc.).

You can follow some steps to set up a git clone of Spotimc using the latest source on the master branch:
https://github.com/mazkolain/spotimc/wiki/Spotimc-Development

Anyway, if you have troubles to setup such environment don't worry. Just email me and I'll prepare a snapshot zip for you.

**Comment by MrFly** [comment]
Done + running. I will give this version a try the next few days and have a look if it crashes. 

Btw: I used the appkey and libs from my old existing beta4 installation. This should be no problem, I think?

Thanks for your help and work!

**Comment by mazkolain-zz** [comment]
There's no problem as long as this appkey is used solely for Spotimc.

Anyway, how is it working now? Has this issue appeared again?

**Comment by MrFly** [comment]
Till now, it works perfect. But I didn't have enough time to test it a long term, only 1-2 hours. In past I'm pretty sure it had crashed playing this playlist. But it looks good I think...

**Comment by alex-caelus** [comment]
It's been working fine for me also. Thank you very much, it's really
appreciated!

**Comment by MrFly** [comment]
Hi,
I'm sorry. I'm not sure if it has to do with this issue, but I noticed the same u mentioned (sometimes not sound on next track) and more urgent:got a crash of xbmc today after pausing my playlist for about 10 minutes and resumed again. There is not a good log entry this time, but I'll add it:

tify-Token=db04967f3849a3be7d1f1b9b0a9cbcfad6817dac&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A97a9f05%29!7:56:54 T:140207386945280  NOTICE: Thread CFileCache start, auto delete: false
7:56:54 T:140207386945280 WARNING: FillBuffer: curl failed with code 33
7:56:54 T:140207386945280   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
7:56:54 T:140207386945280   ERROR: Process, error 115 seeking. seek returned -1
7:56:54 T:140207386945280  NOTICE: Thread CFileCache start, auto delete: false
7:56:54 T:140207386945280 WARNING: FillBuffer: curl failed with code 33
7:56:54 T:140207386945280   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
7:56:54 T:140207386945280   ERROR: Process, error 115 seeking. seek returned -1
7:56:54 T:140207728973568  NOTICE: Thread Jobworker start, auto delete: true
7:59:55 T:140207412123392  NOTICE: Previous line repeats 2 times.
7:59:55 T:140207412123392  NOTICE: Thread CFileCache start, auto delete: false
7:59:55 T:140209232783168   ERROR: Init: Error creating demuxer
7:59:55 T:140207412123392  NOTICE: Thread CFileCache start, auto delete: false
7:59:55 T:140209232783168   ERROR: ADPCMCodec: error opening file http://127.0.0.1:8080/track/5yqtqghLokRgbq8YxYmz7t.wav?idx=12|X-S
tify-Token=db04967f3849a3be7d1f1b9b0a9cbcfad6817dac&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A97a9f05%29!
7:59:55 T:140207412123392  NOTICE: Thread CFileCache start, auto delete: false
7:59:55 T:140207412123392 WARNING: FillBuffer: curl failed with code 33
7:59:55 T:140207412123392   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
7:59:55 T:140207412123392   ERROR: Process, error 115 seeking. seek returned -1
7:59:55 T:140207412123392  NOTICE: Thread CFileCache start, auto delete: false
7:59:55 T:140207412123392 WARNING: FillBuffer: curl failed with code 33
7:59:55 T:140207412123392   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
7:59:55 T:140207412123392   ERROR: Process, error 115 seeking. seek returned -1
8:00:00 T:140207521228544  NOTICE: Thread Jobworker start, auto delete: true
8:01:03 T:140209232783168  NOTICE: Previous line repeats 1 times.
8:01:03 T:140209232783168  NOTICE: NFS is idle. Closing the remaining connections.
8:01:24 T:140207728973568  NOTICE: Thread CFileCache start, auto delete: false
8:01:24 T:140209232783168   ERROR: Init: Error creating demuxer
8:01:24 T:140207728973568  NOTICE: Thread CFileCache start, auto delete: false
8:01:24 T:140209232783168   ERROR: ADPCMCodec: error opening file http://127.0.0.1:8080/track/5ovFM9fUk7ptnIY1msrzBt.wav?idx=13|X-S
tify-Token=db04967f3849a3be7d1f1b9b0a9cbcfad6817dac&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A97a9f05%29!
8:01:24 T:140207728973568  NOTICE: Thread CFileCache start, auto delete: false
8:01:24 T:140207728973568 WARNING: FillBuffer: curl failed with code 33
8:01:24 T:140207728973568   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
8:01:24 T:140207728973568   ERROR: Process, error 115 seeking. seek returned -1
8:01:24 T:140207728973568  NOTICE: Thread CFileCache start, auto delete: false
8:01:24 T:140207728973568 WARNING: FillBuffer: curl failed with code 33
8:01:24 T:140207728973568   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
8:01:24 T:140207728973568   ERROR: Process, error 115 seeking. seek returned -1
8:01:25 T:140207521228544  NOTICE: Thread Jobworker start, auto delete: true
8:02:23 T:140207386945280  NOTICE: Previous line repeats 1 times.
8:02:23 T:140207386945280  NOTICE: Thread CFileCache start, auto delete: false
8:02:24 T:140209232783168   ERROR: Init: Error creating demuxer
8:02:24 T:140207386945280  NOTICE: Thread CFileCache start, auto delete: false
8:02:24 T:140209232783168   ERROR: ADPCMCodec: error opening file http://127.0.0.1:8080/track/0QeEVl1aIDMn8kVUcO1TsP.wav?idx=14|X-S
tify-Token=db04967f3849a3be7d1f1b9b0a9cbcfad6817dac&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A97a9f05%29!
8:02:24 T:140207386945280  NOTICE: Thread CFileCache start, auto delete: false
8:02:24 T:140207386945280 WARNING: FillBuffer: curl failed with code 33
8:02:24 T:140207386945280   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
8:02:24 T:140207386945280   ERROR: Process, error 115 seeking. seek returned -1
8:02:24 T:140207386945280  NOTICE: Thread CFileCache start, auto delete: false
8:02:24 T:140207386945280 WARNING: FillBuffer: curl failed with code 33
8:02:24 T:140207386945280   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
8:02:24 T:140207386945280   ERROR: Process, error 115 seeking. seek returned -1
8:02:24 T:140207521228544  NOTICE: Thread Jobworker start, auto delete: true
8:04:02 T:140208023607040  NOTICE: Thread CFileCache start, auto delete: false
8:04:02 T:140209232783168   ERROR: Init: Error creating demuxer
8:04:02 T:140208023607040  NOTICE: Thread CFileCache start, auto delete: false
8:04:02 T:140209232783168   ERROR: ADPCMCodec: error opening file http://127.0.0.1:8080/track/4JEaqSkDttHk47ypMpvmHM.wav?idx=15|X-S
tify-Token=db04967f3849a3be7d1f1b9b0a9cbcfad6817dac&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A97a9f05%29!
8:04:02 T:140208023607040  NOTICE: Thread CFileCache start, auto delete: false
8:04:02 T:140208023607040 WARNING: FillBuffer: curl failed with code 33
8:04:02 T:140208023607040   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
8:04:02 T:140208023607040   ERROR: Process, error 115 seeking. seek returned -1
8:04:02 T:140208023607040  NOTICE: Thread CFileCache start, auto delete: false
8:04:02 T:140208023607040 WARNING: FillBuffer: curl failed with code 33
8:04:02 T:140208023607040   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
8:04:02 T:140208023607040   ERROR: Process, error 115 seeking. seek returned -1
8:04:03 T:140207728973568  NOTICE: Thread Jobworker start, auto delete: true
8:11:09 T:140209232783168  NOTICE: Previous line repeats 3 times.
8:11:09 T:140209232783168  NOTICE: NFS is idle. Closing the remaining connections.
8:16:40 T:140207521228544  NOTICE: Thread Jobworker start, auto delete: true
8:16:40 T:140207728973568  NOTICE: Thread XBPyThread start, auto delete: false
8:16:40 T:140207728973568  NOTICE: -->Python Interpreter Initialized<--
8:18:23 T:140208023607040 WARNING: FillBuffer: curl failed with code 18
8:18:23 T:140208023607040 WARNING: FillBuffer: Reconnect, (re)try 1
OpenELEC:~/.xbmc/temp #

Thank you!

**Comment by mazkolain-zz** [comment]
@MrFly,

The crash you experienced when pausing the track could be related to the fact that seeking is not implemented yet (issue https://github.com/mazkolain/spotimc/issues/37).

Regarding the no sound issue, I remember you set up a development version containing the fix for this issue. Are you still running that development version and the issue has appeared again? Or it was related only to the pause issue?

**Comment by MrFly** [comment]
Hi,

Ok, didn't realize that seeking and pausing are the same in this case. I'm still running the dev version, and from time to time the track is silent, but is still running... It is very very are that this happens.
