### ISSUE TITLE
ParseError starting Spotimc

### ISSUE THREAD

**Issue by peterwalker78** [mazkolain-zz/spotimc#159]
Yesterday I started receiving this error when I try to start up Spotimc:

'ParseError - not well-formed (invalid token): line 150, column 1

Below are the relevant lines from kodi.log:

19:02:56 T:2780820512  NOTICE: -->Python Interpreter Initialized<--
19:02:57 T:2797597728  NOTICE: Thread LanguageInvoker start, auto delete: false
19:02:58 T:2797597728  NOTICE: -->Python Interpreter Initialized<--
19:02:58 T:2797597728 WARNING: CPythonInvoker(12): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
19:03:05 T:2797597728   ERROR: Traceback (most recent call last):
19:03:05 T:2797597728   ERROR:   File "/home/osmc/.kodi/addons/script.audio.spotimc/resources/libs/spotimcgui/main.py", line 497, in main
19:03:05 T:2797597728   ERROR:     fm.install_file(xml_path, font_dir)
19:03:05 T:2797597728   ERROR:   File "/home/osmc/.kodi/addons/script.audio.spotimc/resources/libs/xbmc-skinutils/src/skinutils/fonts.py", line 191, in install_file
19:03:05 T:2797597728   ERROR:     self._install_file(doc_cache, user_file, skin_file, font_path)
19:03:05 T:2797597728   ERROR:   File "/home/osmc/.kodi/addons/script.audio.spotimc/resources/libs/xbmc-skinutils/src/skinutils/fonts.py", line 161, in _install_file
19:03:05 T:2797597728   ERROR:     self._get_font_attr(item, "linespacing")
19:03:05 T:2797597728   ERROR:   File "/home/osmc/.kodi/addons/script.audio.spotimc/resources/libs/xbmc-skinutils/src/skinutils/fonts.py", line 100, in _install_font_def
19:03:05 T:2797597728   ERROR:     font_doc = self.__doc_cache.read(skin_file)
19:03:05 T:2797597728   ERROR:   File "/home/osmc/.kodi/addons/script.audio.spotimc/resources/libs/xbmc-skinutils/src/skinutils/__init__.py", line 341, in read
19:03:05 T:2797597728   ERROR:     self.__cached_docs[file] = ET.parse(file)
19:03:05 T:2797597728   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
19:03:05 T:2797597728   ERROR:     tree.parse(source, parser)
19:03:05 T:2797597728   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
19:03:05 T:2797597728   ERROR:     parser.feed(data)
19:03:05 T:2797597728   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
19:03:05 T:2797597728   ERROR:     self._raiseerror(v)
19:03:05 T:2797597728   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
19:03:05 T:2797597728   ERROR:     raise err
19:03:05 T:2797597728   ERROR: ParseError: not well-formed (invalid token): line 150, column 1
19:03:08 T:2797597728  NOTICE: Thread LanguageInvoker start, auto delete: false
19:03:08 T:2797597728  NOTICE: Previous line repeats 1 times.
19:03:08 T:2797597728  NOTICE: -->Python Interpreter Initialized<--
19:03:10 T:2814374944  NOTICE: Previous line repeats 1 times.
19:03:10 T:2814374944  NOTICE: Thread JobWorker start, auto delete: true
19:03:10 T:2814374944 WARNING: CreateLoader - unsupported protocol(home/image) in home/image://%2fhome%2fosmc%2f.kodi%2faddons%2fscript.audio.spotimc%2ficon.png/

I absolutely LOVE this addon, so I'm traumatised not to have it at the moment :(

Let me know if you need any other info.

Thanks a million,
Peter.

**Comment by malfurion** [comment]
i think theres something wrong with your settings file

delete your configurations so it will fix it maybe

on linux-ubuntu the configs are at /home/<username>/.kodi/userdata/addon_data/

and there is a folder named script.audio.spotimc

delete this folder then you have to reconfigure your addon but this will perhaps fix you problem

**Comment by mazkolain-zz** [comment]
Hi,

This could be related to a skin compatibility issue. Which Kodi skin are you using?

**Comment by peterwalker78** [comment]
I tried that, however it didn't resolve the issue. I re-installed osmc, and now it works again, so it must have been some weird environmental issue. Thanks for the suggestions though. Now loving Spotimc again :)

Peter.

**Comment by peterwalker78** [comment]
Following a system update, I now have the exact same error again. I'm running osmc with the default osmc skin.

**Comment by hcaltenco** [comment]
I have the exact same error message. Fresh installation of OSMC in RPi with the default skin. Any help would be appreciated

**Comment by malfurion** [comment]
Same error here with osmc using confluence skin

On kodi for linux it works

**Comment by cortex93** [comment]
Commenting the line resources/libs/spotimcgui/main.py:497 do the trick.
But I don't know understand why the parser is complaining. For me, its line 158 (osmc confluence skin).

**Comment by cortex93** [comment]
Spot the offending file in confluence skin. addons/skin.confluence/720p/Font.xml has some malformed xml comment < -- --> without !

**Comment by peterwalker78** [comment]
You're a genius cortex93!! Editing the Font.xml file for my active skin, and correcting the commenting (changing < -- to <!-- ) has fixed it! :)

Thank you so much!

**Comment by mazkolain-zz** [comment]
Thanks @cortex93 for the information!

Anyway, when Confluence gets updated you will probably face the same error again (updates overwriting Font.xml and reintroducing the malformed comment).

Looks like I will have to add a quickfix for the skin loading code preventing this case (the skin code is actually full of these quirks).

I'll keep this issue open until the quickfix is introduced.

**Comment by cortex93** [comment]
Yes, a better fix would be to update the sanitazing regex in skinutils. But the strange things is why xbmc is actually loading it and be so tolerant in the first place.

**Comment by peterwalker78** [comment]
I have also noticed that the comments disappear entirely from the file after spotimc loads successfully for the first time after fixing the comments.

**Comment by mazkolain-zz** [comment]
Yes, Spotimc touches these files during startup, and one of these changes is to remove their comments, if it finds that they may probably cause xml parse errors.

Anyway, these files are all restored to their original state when Spotimc exits.

**Comment by peterwalker78** [comment]
On my system the file does not appear to be restored on exit. I do have a backup file in the same directory (Font.xml-skinutilsbackup). This doesn't cause any problems as far as I can tell though.

**Comment by Sorrgath** [comment]
Didn't work for me, changed the comment in the active skin. error still occurs. Did i miss sth?

**Comment by peterwalker78** [comment]
Can you link to a pastebin of your file please?
