### ISSUE TITLE
libspotify missing (?) on android

### ISSUE THREAD

**Issue by fumantsu** [mazkolain-zz/spotimc#166]
Hello,

I'm receiving this error message on first run. I have confirm that the file exists under linux dir (maybe needs android folder (?))

Log from Kodi.

02648   ERROR: Traceback (most recent call last):
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/spotimcgui/main.py", line 509, in main
17:25:55 T:1562802648   ERROR:     gui_main(**addon_path**)
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/spotimcgui/main.py", line 393, in gui_main
17:25:55 T:1562802648   ERROR:     initially_unload_playlists=False,
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/spotify/session.py", line 310, in **init**
17:25:55 T:1562802648   ERROR:     err = self.**session_interface.create(ctypes.byref(config), ctypes.byref(self.__session_struct))
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/session.py", line 129, in create
17:25:55 T:1562802648   ERROR:     ctypes.POINTER(config), ctypes.POINTER(ctypes.c_void_p)
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/__init**.py", line 73, in _get_func
17:25:55 T:1562802648   ERROR:     lib = self.get_library()
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/__init__.py", line 66, in get_library
17:25:55 T:1562802648   ERROR:     self.**library = self._load_library()
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/__init**.py", line 91, in _load_library
17:25:55 T:1562802648   ERROR:     return ll.load('libspotify')
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/__init__.py", line 189, in load
17:25:55 T:1562802648   ERROR:     _library_cache[name] = self._load(name)
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/__init__.py", line 183, in _load
17:25:55 T:1562802648   ERROR:     return self._load_from_sys_path(loader, name)
17:25:55 T:1562802648   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.audio.spotimc/resources/libs/pyspotify-ctypes/src/_spotify/__init__.py", line 165, in _load_from_sys_path
17:25:55 T:1562802648   ERROR:     raise OSError("Unable to find '%s'" % name)
17:25:55 T:1562802648   ERROR: OSError: Unable to find 'libspotify'
17:25:56 T:1562802648   ERROR: Exception
17:25:56 T:1562802648   ERROR: OSError
17:25:56 T:1562802648   ERROR: :
17:25:56 T:1562802648   ERROR: OSError("Unable to find 'libspotify'",)
17:25:56 T:1562802648   ERROR:  in
17:25:56 T:1562802648   ERROR: <bound method ?.? of <spotify.session.Session instance at 0x643d8758>>

**Comment by mazkolain-zz** [comment]
Spotimc with the Android Spotify lib is very unstable. That's why it was not shipped on the official download package.

If you still want to give it a try, here are some instructions:
1. Grab the Android Spotify lib from here:
   https://developer.spotify.com/technologies/libspotify/
2. On the tar file, locate libspotify.so.12.1.51, copy it to dlls/android/ on the Spotimc installation folder and rename it to libspotify.so.
3. Now run Spotimc as usual.

As said, past experiences with this lib where too unstable. Also note that libspotify for Android is in beta status (libspotify itself is considered deprecated).

Regards,

Mikel
