### ISSUE TITLE
Fails to load on raspbmc (XBMC 12 Final)

### ISSUE THREAD

**Issue by WizX20** [mazkolain-zz/spotimc#95]
The add-on installation runs just fine, it actually restarts the pi by itself. But when you try to load spotimc it exits with a script error:

15:45:36 T:2713711680  NOTICE: -->Python Interpreter Initialized<--
15:45:37 T:2713711680  NOTICE: /home/pi/.xbmc/addons/skin.confluence/write_test.txt
15:45:37 T:2713711680   ERROR: /home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/fonts.py:138: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
15:45:37 T:2713711680  NOTICE: /home/pi/.xbmc/addons/skin.confluence/write_test.txt
15:45:37 T:2713711680  NOTICE: install include: /home/pi/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
15:45:42 T:3038208000   ERROR: ClearBlock: Trying to clear non existent block /home/pi/.xbmc/addons/script.audio.spotimc
15:45:42 T:3038208000   ERROR: Previous line repeats 1 times.
15:45:42 T:3038208000 WARNING: Cleanup: Having to cleanup texture button-nofocus.png
15:45:42 T:3038208000 WARNING: Cleanup: Having to cleanup texture button-focus.png
15:45:49 T:3038208000   ERROR: ClearBlock: Trying to clear non existent block /home/pi/.xbmc/addons/script.audio.spotimc
15:45:59 T:3038208000   ERROR: Previous line repeats 3 times.
15:45:59 T:3038208000 WARNING: GetLabel - Unknown nodetype requested 0
15:45:59 T:2636117056 WARNING: Previous line repeats 1 times.
15:45:59 T:2636117056  NOTICE: Thread Background Loader start, auto delete: false
15:45:59 T:2713711680   ERROR: Exception
15:45:59 T:2713711680   ERROR: OSError
15:45:59 T:2713711680   ERROR: :
15:45:59 T:2713711680   ERROR: OSError("Unable to find 'libspotify'",)
15:45:59 T:2713711680   ERROR:  in
15:45:59 T:2713711680   ERROR: <bound method ?.? of <spotify.session.Session instance at 0x3b07f08>>
15:45:59 T:2713711680   ERROR:  ignored
15:45:59 T:2713711680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: Unable to find 'libspotify'
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/default.py", line 77, in <module>
                                                main(**addon_path**)
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/spotimcgui/**init**.py", line 313, in main
                                                initially_unload_playlists=False,
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/spotify/session.py", line 312, in **init**
                                                err = self.**session_interface.create(ctypes.byref(config), ctypes.byref(self.__session_struct))
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/session.py", line 129, in create
                                                ctypes.POINTER(config), ctypes.POINTER(ctypes.c_void_p)
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init**.py", line 95, in _get_func
                                                return self._get_func2(name, name, restype, *argtypes)
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 85, in _get_func2
                                                lib = self.get_library()
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 66, in get_library
                                                self.**library = self._load_library()
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init**.py", line 111, in _load_library
                                                return ll.load('libspotify')
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 209, in load
                                                _library_cache[name] = self._load(name)
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 203, in _load
                                                return self._load_from_sys_path(loader, name)
                                              File "/home/pi/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 185, in _load_from_sys_path
                                                raise OSError("Unable to find '%s'" % name)
                                            OSError: Unable to find 'libspotify'
                                            -->End of Python script error report<--
15:46:00 T:3038208000   ERROR: ClearBlock: Trying to clear non existent block /home/pi/.xbmc/addons/script.audio.spotimc
15:46:05 T:2713711680  NOTICE: Thread Background Loader start, auto delete: false
15:46:14 T:2713711680  NOTICE: Thread Jobworker start, auto delete: true

**Comment by WizX20** [comment]
This seems to fix it: http://forum.stmlabs.com/showthread.php?tid=921&pid=50586#pid50586)
Patched libspotify: https://dl.dropbox.com/u/60928807/libspotify.so
